uorover_arm:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.05
  kinematics_solver_attmpets: 5
  max_cache_size: 10000
  min_pose_distance: 1.0
  min_joint_config_distance: 4.0
  position_only_ik: true
